stages:
  - Release

#
# Release targets
#

Distribution:
  stage: Release
  only:
    refs:
      - tags
      - master
  image: rakudo-star
  script:
    - echo "NOOP"
  artifacts:
    name: App-CPAN-${CI_COMMIT_TAG}
    paths:
      - META6.json
      - lib
      - bin
      - t
      - resources

Docker:
  stage: Release
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
